### PR TITLE
Changed note category font size.

### PR DESCRIPTION
**Pull request by przemekblasiak**
Hey bro, I've made a few adjustments here and there, it looks way better now, no bullshit man!

### CODE REVIEW

**Comment by mattdrzazga** [comment]
Yo, let me talk about this with my associates. BRB

**Comment by mattdrzazga** [comment]
The say this is pure gibberish and not like you stated before 'no bullshit'.

**Comment by przemekblasiak** [comment]
They must be kidding me man, take a closer look yourself.

Before:
before

After:
after

**Comment by mattdrzazga** [comment]
Ok, you got me with the line 'I'm buying next pizza in Da Grasso'.
Thank you Sean.
Merging.

**Pull request merged**
